# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a11fae67bc2db0efaaaf77327b127d27a38b63172b242f9e267e2d816d315381a5f8ca264091cdede9099b88966e389b553bfb4723d1576b1fbed6c2f049ca4

test:
  secret_key_base: b22fd44217a7880b9ce27c4e20bfd55892ec8d7903b9c677e4249f96e4f892ffc3c70995ecf8f2b005d00a87275377a02d364de2c060c22a3adc2a214d4995dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
